locals {
  vpc_cidr          = "${var.vpc_cidr_prefix}.0.0/16"
  pub_subnet1_cidr  = "${var.vpc_cidr_prefix}.9.0/24"
  pub_subnet2_cidr  = "${var.vpc_cidr_prefix}.10.0/24"
  pub_subnet3_cidr  = "${var.vpc_cidr_prefix}.11.0/24"
  priv_subnet1_cidr = "${var.vpc_cidr_prefix}.12.0/24"
  priv_subnet2_cidr = "${var.vpc_cidr_prefix}.13.0/24"
  priv_subnet3_cidr = "${var.vpc_cidr_prefix}.14.0/24"
  subnet1_zone      = "us-east-1a"
  subnet2_zone      = "us-east-1b"
  subnet3_zone      = "us-east-1c"
  pub_subnet1_tag   = "${var.project_name}-${var.environment}-public-subnet-1"
  pub_subnet2_tag   = "${var.project_name}-${var.environment}-public-subnet-2"
  pub_subnet3_tag   = "${var.project_name}-${var.environment}-public-subnet-3"
  priv_subnet1_tag  = "${var.project_name}-${var.environment}-private-subnet-1"
  priv_subnet2_tag  = "${var.project_name}-${var.environment}-private-subnet-2"
  priv_subnet3_tag  = "${var.project_name}-${var.environment}-private-subnet-3"
  igw_tag           = "${var.project_name}-${var.environment}-igw"
  pub_rt_tag        = "${var.project_name}-${var.environment}-public-rt"
  priv_rt_tag       = "${var.project_name}-${var.environment}-private-rt"
}
